name: 'bot'
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0/1 * * *
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
          cache: 'maven'
      - name: package
        run: mvn clean package
      - name: set env secret
        env: 
          LOCALCOOKIE: ${{ secrets.LOCALCOOKIE }}
          REFRESHTOKEN: ${{ secrets.REFRESHTOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: run
        run: java -jar dynamics-auto-likes-1.0-SNAPSHOT.jar -Dapp.localCookie=${{ env.LOCALCOOKIE }} -Dapp.refreshToken=${{ env.REFRESHTOKEN }} -Dapp.username=${{ env.USERNAME }} -Dapp.password=${{ env.PASSWORD }}
