name: 'bot'
on: 
  schedule:
    - cron: 0 0/1 * * *
jobs:
  start:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checout@v4
      - name: set jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
          cache: 'maven'
      - name: package
        run: mvn clean package

      - name: run
        run: java -jar dynamics-auto-likes-1.0-SNAPSHOT.jar -Dapp.localCookie=${{ app.localCookie }} -Dapp.refreshToken=${{ app.refreshToken }} -Dapp.username=${{ app.username }} -Dapp.password=${{ app.password }}
