
# https://rhysd.github.io/actionlint/   语法检查
name: 'bot'
on: 
  push:
    branches: [ main ]
  # schedule:
  #   - cron: 0 0/1 * * *
jobs:
  start:
    environment: bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
          cache: 'maven'
      - name: package
        env: 
          LOCALCOOKIE: ${{ secrets.LOCALCOOKIE }}
          REFRESHTOKEN: ${{ secrets.REFRESHTOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: mvn clean package && java -jar target/dynamics-auto-likes-1.0-SNAPSHOT.jar -Dapp.localCookie=${{ env.LOCALCOOKIE }} -Dapp.refreshToken=${{ env.REFRESHTOKEN }} -Dapp.username=${{ env.USERNAME }} -Dapp.password=${{ env.PASSWORD }}
